apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  username: YWRtaW4=  # Base64 for "admin"
  password: c3VwZXJzZWN1cmVwYXNzd29yZA==  # Base64 for "supersecurepassword"
